### ISSUE TITLE
The bundled 7z.exe doesn't work for me

### ISSUE THREAD

**Issue by ghost** [Wesley-Chan/GTK-for-Windows#1]
The included 7z.exe errors out with "cannot find the code that works with archives" for me.  Perhaps it's missing 7z.dll?  Replacing 7z.exe with the one I already had installed on my system and copying my 7z.dll into the tools folder allowed me to proceed.

**Comment by Wesley-Chan** [comment]
That exe is just the official one.

I tried to clear out the PATH ENV variable by

```
set PATH=
```

So it can't link to any dlls when it runs. And I ran this command under /z_Install

```
.\Tools\7z.exe x ..\MSYS\findutils-4.4.2-2-msys-1.0.13-bin.tar.lzma -o.\cache
```

And the command prompt says

> 7-Zip 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
> 
> Processing archive: ..\MSYS\findutils-4.4.2-2-msys-1.0.13-bin.tar.lzma
> 
> Extracting  findutils-4.4.2-2-msys-1.0.13-bin.tar
> 
> Everything is Ok
> 
> Size:       460800
> Compressed: 125977

Seems alright.

Could you please try this on another PC? I tried these scripts on two PCs and they both work smoothly. Please let me know if this still happens. Thank you.

**Comment by Digi59404** [comment]
I can confirm this also does not work for me. Replace the 7zip with the file here - http://www.7-zip.org/a/7za920.zip That's the correct Command Line 7z

**Comment by Wesley-Chan** [comment]
Thanks, Digi59404. I made a commit to replace that.
