### ISSUE TITLE
64-bit does not work

### ISSUE THREAD

**Issue by dboggs95** [Wesley-Chan/GTK-for-Windows#10]
I tried a 64-bit compiler. It does not work. 
After messing around with it for days, I found that some of the scripts needed to be told it is a 64-bit build, but I still can't get it built.
At least update the FAQ so folks know 64-bit does not work. Right now it just says, "it depends on which compiler you choose."

**Comment by Wesley-Chan** [comment]
Thanks for your feedback. If you look closer to the setup.bat, it told you 64-bit is not tested. Will make it explicit in the FAQ though.

And, by the way, SigC++ 2.99 name the pkg-config file to be version 3. So glibmm won't find it. If anyone is trying to build gtkmm at this moment, rename it back yourself. I'll fix these peoblems as soon as I have free time.
