### ISSUE TITLE
GTK+ with classic Windows GUI

### ISSUE THREAD

**Issue by HackMemory** [Wesley-Chan/GTK-for-Windows#12]
Hello! In GTK+ 3.6.4 was a standard gui of Windows. How can i return it? Tnx!

**Comment by Wesley-Chan** [comment]
Return it? Can you elaborate?

**Comment by HackMemory** [comment]
http://blogs.gnome.org/alexl/files/2011/11/widget-factor1.png
It`s classical gui of Windows and it isn`t theme

**Comment by Wesley-Chan** [comment]
Are you sure it isn't just a theme? You should post this on GTK+'s mailing-list. People there will recognize it.
