### ISSUE TITLE
could you add a getting started guide?

### ISSUE THREAD

**Issue by PerfectCarl** [Wesley-Chan/GTK-for-Windows#2]
With the requirements and how to build gtk and what are the binaries produced, where, how to bundle them (or create an installation program)...

I would be glad to test the guide and test it as I need gtk for windows.

**Comment by Wesley-Chan** [comment]
Hi PerfectCarl,

There're documents on wiki pages. Click [here](https://github.com/Wesley-Chan/GTK-for-Windows/wiki/Instructions). Are they helping? If not, I'll consider rewrite them to be clear enough and I'm going to need your support. Thanks.

**Comment by PerfectCarl** [comment]
Oh the wiki pages. I haven't thought to check them out:) 

Thanks for your quick reply.
I'll look into those pages and will likely build gtk for windows in the coming months.

I'll keep you posted how things are going and if things need to be added, I'll submit PR for the documentation if that's OK with you.
