### ISSUE TITLE
LibPNG is our of date

### ISSUE THREAD

**Issue by Digi59404** [Wesley-Chan/GTK-for-Windows#3]
LibPNG 1.6.14's archive gets downloaded and is corrupted. This can be resolved by swapping it with LibPNG 1.1.16 located here => http://sourceforge.net/projects/libpng/files/libpng16/1.6.16/libpng-1.6.16.tar.xz/download

**Comment by Wesley-Chan** [comment]
Thanks for your information. Just updated.
