### ISSUE TITLE
how to compile last stable release of GTK?

### ISSUE THREAD

**Issue by ghost** [Wesley-Chan/GTK-for-Windows#4]
I have looked through the wiki, but there is no mention of compiling the latest stable release (in this case 3.14). And looking through the commit messages multiple files have been updated to support GTK 3.15.2.

If I used the source for 3.14 instead, would that cause anything to break?

**Comment by Wesley-Chan** [comment]
Wow, so many people complain about the wiki pages. Will rewrite them.
If you just replace GTK+ 3.15.2 with 3.14.x, just go ahead. It would be no problem. And also, you have to modify `libs/gtk+.sh`.
