### ISSUE TITLE
atk configure error (GLIB)

### ISSUE THREAD

**Issue by sharro** [Wesley-Chan/GTK-for-Windows#7]
Hello!

Sorry if I ask dummy question, I'm not well-known with MSYS and pkg-config. atk (and some other deps) gives an error when configuring:

```
checking for GLIB - version >= 2.31.2... 
*** 'pkg-config --modversion glib-2.0' returned 2.45.1, but GLIB (2.34.3)
*** was found! If pkg-config was correct, then it is best
*** to remove the old version of GLib. You may also be able to fix the error
*** by modifying your LD_LIBRARY_PATH enviroment variable, or by editing
*** /etc/ld.so.conf. Make sure you have run ldconfig if that is
*** required on your system.
*** If pkg-config was wrong, set the environment variable PKG_CONFIG_PATH
*** to point to the correct configuration files
no
configure: error: 
*** GLIB 2.31.2 or better is required. The latest version of
*** GLIB is always available from ftp://ftp.gtk.org/. If GLIB is installed
*** but not in the same location as pkg-config add the location of the file
*** glib-2.0.pc to the environment variable PKG_CONFIG_PATH.
```

I can't find any GLIB files with version 2.34.3, I also can't find file /etc/ld.so.conf or existing variable LD_LIBRARY_PATH. GLIB compiles and installs well, if I don't miss something in it's log.

How can I solve this problem? And is it possible to share precompiled GTK bundle with us? Some file hostings allow big files for free, like MEGA.

Thank you,
Alexander.

**Comment by Wesley-Chan** [comment]
It does? OK, I'll check it.
And yes, there's a precompiled bundle. [Here](http://stackoverflow.com/questions/6006689/where-can-i-download-precompiled-gtk-3-binaries-or-windows-installer).

Update:
Nope. I have no problem with that. Here's my log.

```
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for bind_textdomain_codeset... no
checking for some Win32 platform... yes
checking for native Win32 platform... yes
checking for windres... windres
checking for lib.exe... no
checking for aclocal flags... 
checking for pkg-config... /opt/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for GLIB - version >= 2.31.2... yes (version 2.45.2)
checking for DEP... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for LC_MESSAGES... no
checking libintl.h usability... yes
```

And I checked all my commit histories. I have never submitted a GLib of version 2.34.3. It must be coming from somewhere of your computer.
Did you follow the [instructions](https://github.com/Wesley-Chan/GTK-for-Windows/wiki/Instructions)? Please remove all the files and try again.

**Comment by sharro** [comment]
Sorry for late answer.

Many thanks for the precompiled GTK url!

I followed Instructions page, also I tried once more time with full wipe. I has both MSYS and MSYS2 packages installed, but I removed them from %PATH% (and cygwin and all of my MinGW compilers). Right now I trying to build GTK on another PC, will update this post with results.

P.S: sorry for my English, it's foreign language for me.

**Comment by Wesley-Chan** [comment]
> I has both MSYS and MSYS2 packages installed, but I removed them from %PATH%

Yeah, that would be a nice try. Good luck.
