### ISSUE TITLE
icon-naming-utils 404

### ISSUE THREAD

**Issue by Digi59404** [Wesley-Chan/GTK-for-Windows#9]
It appears tango.freedesktop.org has removed this package. it's 404ing and all links to it 404.

**Comment by Digi59404** [comment]
Perhaps replace with? https://www.archlinux.org/packages/extra/any/icon-naming-utils/download/

**Comment by Wesley-Chan** [comment]
Thanks for the feedback.

I think their server is down. Please download it [here](https://sources.archlinux.org/other/icon-naming-utils/icon-naming-utils-0.8.90.tar.gz).
